server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ms-user
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    addresses: amqps://qsfmdfvx:mS0wWKuNKvp14zLHTdFCMK0rFA7sSzOR@beaver.rmq.cloudamqp.com/qsfmdfvx


broker:
  queue:
    email:
      name: default.email